### ISSUE TITLE
[FEAT REQUEST]: Addtional Variables

### ISSUE THREAD

**Issue by jmcc94** [bitfocus/companion-module-netgear-avline#6]
Is it possible to get variables per port?

Especially;
- Speed
- POE Active
- POE Draw

**Comment by bryce-seifert** [comment]
These all seems possible, I can start working on them if you haven't already


For Speed, what specific unit are you looking for? Seems the options are
```
* `1` = SP10
* `2` = SP100
* `3` = SP1000 * `4` = SP10G
```

Or

```
* `1` = SPEED_AUTO_NEG
* `2` = SPEED_HALF_100TX
* `3` = SPEED_FULL_100TX
* `4` = SPEED_HALF_10T
* `5` = SPEED_FULL_10T
* `6` = SPEED_FULL_100FX
* `7` = SPEED_FULL_1000SX * `8` = SPEED_FULL_10GSX
* `9` = SPEED_FULL_20GSX
* `10` = SPEED_FULL_40GSX * `11` = SPEED_FULL_25GSX * `12` = SPEED_FULL_50GSX * `13` = SPEED_FULL_100GSX * `14` = SPEED_AAL5_155
* `15` = SPEED_FULL_5FX
* `128` = SPEED_FULL_2P5FX * `129` = SPEED_LAG
* `130` = SPEED_UNKNOWN
```

**Comment by jmcc94** [comment]
No, haven't started..

I was thinking real-time info, so probably what you would get from GET /sw_portstats...

And /swcfg_poe for currentPower...

**Comment by bryce-seifert** [comment]
@jmcc94 I have the poe status and poe power ready to go in https://github.com/bitfocus/companion-module-netgear-avline/pull/7

For the speed, the options are a bit confusing from /sw_portstats
The "speed" output is just things like
* `1` = SPEED_AUTO_NEG
* `2` = SPEED_HALF_100TX
* `3` = SPEED_FULL_100TX
* `4` = SPEED_HALF_10T
* `5` = SPEED_FULL_10T
* `6` = SPEED_FULL_100FX

There's also rxMbps and txMbps which should reviece rates, but if they're nominal (in Kbps) it just shows 0.0

What would be most helpful?

**Comment by jmcc94** [comment]
@bryce-seifert Thanks!

I was hoping that the speed showed the negotiated speed... and it would be parsed down to one of the following - 10/100/1000/110G/20G/25G/40G/50G/100G

I wouldn't worry about the Half/Full duplex info...

**Comment by bryce-seifert** [comment]
@jmcc94 These variables should be in the next beta build. Let me know if you'd like any changes, or run into any issues

**Comment by jmcc94** [comment]
Perfect. Thank you
